CREATE DATABASE [12313]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'12313', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\12313.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'12313_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\12313_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 WITH LEDGER = OFF
GO
ALTER DATABASE [12313] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [12313] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [12313] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [12313] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [12313] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [12313] SET ARITHABORT OFF 
GO
ALTER DATABASE [12313] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [12313] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [12313] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [12313] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [12313] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [12313] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [12313] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [12313] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [12313] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [12313] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [12313] SET  DISABLE_BROKER 
GO
ALTER DATABASE [12313] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [12313] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [12313] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [12313] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [12313] SET  READ_WRITE 
GO
ALTER DATABASE [12313] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [12313] SET  MULTI_USER 
GO
ALTER DATABASE [12313] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [12313] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [12313] SET DELAYED_DURABILITY = DISABLED 
GO
USE [12313]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [12313]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [12313] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
